### ISSUE TITLE
Found this helpful

### ISSUE THREAD

**Issue by pcuci** [ML4VIS/ML4VIS.github.io#5]
Thanks for the fun UI! Was tricky to get to use the app in the beginning, but once you understand what the tags mean, the landscape starts to make sense :-)

**Comment by wangqianwen0418** [comment]
Hi Paul, glad that you found ML4VIS helpful!
Can you share what makes you confused at the beginning to help us improve the interface?

You are also welcome to add new papers through PR. We will publish a new version, hopefully this summer, to include more latest studies.

**Comment by pcuci** [comment]
I'm new to the field, and am not familiar with your categorization, why these tags exactly?

Wonder if we could categorize/tag differently, maybe ChatGPT the contents of the papers to sort out "more intuitive" tags?

Looking forward to the updated set of papers!
