### ISSUE TITLE
Suggest Paper: [Learned Data-aware Image Representations of Line Charts for Similarity Search]

### ISSUE THREAD

**Issue by Thanksyy** [ML4VIS/ML4VIS.github.io#6]
**Learned Data-aware Image Representations of Line Charts
for Similarity Search, http://dbgroup.cs.tsinghua.edu.cn/ligl/papers/linenet.pdf, SIGMOD 2023**

**This paper investigates the fine-grained similarity search of line charts, which contributes to the field of similarity search of visualizations**

**This paper first proposes LineNet, a novel Vision Transformer-based Triplet Autoencoder model to
learn data-aware image representations of line charts by leveraging both the underlying data and
rendered images of line charts. It further designs a diversified training samples selection algorithm to make the learning process more effective. This paper contributes a large-scale line chart corpus, namely LineBench, which has more
than 115K line charts and the metadata from four real-world datasets.**

**Learned fine-grained visualization representations for similarity search of visualization charts.*

*N/A**

**Comment by wangqianwen0418** [comment]
Thanks @Thanksyy , the suggested paper has been added
